### ISSUE TITLE
ModernBox not working on Access 2016 x64

### ISSUE THREAD

**Issue by yankarinRG** [GustavBrock/VBA.ModernBox#1]
Hello Gustav, is it normal your code is not working on Access 2016 x64? I tried correcting function calling adding PtrSafe and replacing function or sub data type with LongPtr instead of Long but nothing.
Thank you, I would really like to use this!

**Comment by GustavBrock** [comment]
Honestly, I don't know as I never run Office 64-bit. The steps you have taken sounds like those normally needed. Also, the few API calls made should be nothing special.
I will have to fire up an Access 64-bit but I cannot tell when that would happen. It is, however, already on my to-do list; unfortunately, this is very long.

**Comment by yankarinRG** [comment]
Thank you for replying back, Gustav :)

**Comment by yankarinRG** [comment]
Hello Gustav, I managed to get it working..... more or less!
1. First of all I downloaded the one from experts-exchange.com, becaue here on github it's missing the forms.
2. I then added "ptrsafe" after every declare, literally.

The only problem is, maybe it's related becaue I'm not using English as main language, the MsgMox is completely missing captions inside the buttons.
It writes an empty string inside each buttons I don't know why though...

Any help is appreciated!

P.S. I tested with english set as Access's default's language and the captions are still blank.

**Comment by GustavBrock** [comment]
That is good news.

First, the forms are there, the *.cls files, but I should make a note, that these must be imported in Access with the command _SaveFromText_.

Second, adding ptrSafe for all declarations is what I have heard is a must.

Third, the button captions are - as you probably have found out - retrieved by the function _FillCaptions_ as described in the article under the paragraph "Localized captions". It should work for any localization, and _User32.dll_ is the file to call even under 64-bit as discussed here: [Invoking user32.dll on a 64 bit system](http://stackoverflow.com/questions/1540741/c-sharp-pinvoking-user32-dll-on-a-64-bit-system).

You could try to call with other caption ID than FirstCaptionId and LastCaptionId. If no success, please let me know, and I can try to research the issue.

Thanks for your findings.

**Comment by yankarinRG** [comment]
Hello Gustav, I tried creating a test form with a button that, if pressed, shows the caption corresponding to the index. I tried with some, but it looks like the _LoadString_ call doesn't produce a result.

Example form: [http://www.filedropper.com/database4](url)

Yan

**Comment by GustavBrock** [comment]
Sounds right. I've researched a little on LoadString but found exactly nothing related to issues or different behaviour under 64-bit. 
I'll have to get back with this. Thanks for narrowing it down.

**Comment by yankarinRG** [comment]
Hey again, analyzing deeper with _Err.LastDLLError_ I found that, after the _LoadString_ call it produces either one or the other:

> ERROR_RESOURCE_DATA_NOT_FOUND
> 1812 (0x714)
> The specified image file did not contain a resource section.
> ERROR_RESOURCE_TYPE_NOT_FOUND
> 1813 (0x715)
> The specified resource type cannot be found in the image file.

~~P.S. I opened up user32 with ResEdit and found there is no string table in it, that could be the problem..~~

**Comment by GustavBrock** [comment]
I have no explanation for that. But, of course, with those errors, no captions will be retrieved.

**Comment by yankarinRG** [comment]
Hello Gustav, I finally managed to get it working 100% on 64 bit. I tested it on a 32bit Office 2010 and it seems to work.
Here's all it needs to be done:

1) Add PtrSafe when you Declare an API function
2) Change Long to LongPtr in as the LoadLibrary API call data type (and edit the variables and the other related lines of code as well)

It's really cool now!

**Comment by GustavBrock** [comment]
That is great news. Thank you so much for clearing it up - I don't know when I would have found the time for working with this.
I'll add the changes when I have an Access 64-bit up and running.
